
phanThomasA3: mainA3.o createTweet.o displayTweets.o searchTweetsByKeyword.o countStopWords.o deleteTweet.o saveTweetsToFile.o loadTweetsFromFile.o sortID.o addNodeToList.o displayMenu.o matchStopWords.c countTweets.c deleteInsertNode.c insertNode.c freeTweets.c
	gcc mainA3.o createTweet.o displayTweets.o searchTweetsByKeyword.o countStopWords.o deleteTweet.o saveTweetsToFile.o loadTweetsFromFile.o sortID.o addNodeToList.o displayMenu.o matchStopWords.c countTweets.c deleteInsertNode.c insertNode.c freeTweets.c -o phanThomasA3

mainA3.o: mainA3.c headerA3.h extraHeaderA3.h
	gcc -Wall -std=c99 -c mainA3.c

createTweet.o: createTweet.c headerA3.h extraHeaderA3.h
	gcc -Wall -std=c99 -c createTweet.c

displayTweets.o: displayTweets.c headerA3.h extraHeaderA3.h
	gcc -Wall -std=c99 -c displayTweets.c

searchTweetsByKeyword.o: searchTweetsByKeyword.c headerA3.h extraHeaderA3.h
	gcc -Wall -std=c99 -c searchTweetsByKeyword.c

countStopWords.o: countStopWords.c headerA3.h extraHeaderA3.h
	gcc -Wall -std=c99 -c countStopWords.c

deleteTweet.o: deleteTweet.c headerA3.h extraHeaderA3.h
	gcc -Wall -std=c99 -c deleteTweet.c

saveTweetsToFile.o: saveTweetsToFile.c headerA3.h extraHeaderA3.h
	gcc -Wall -std=c99 -c saveTweetsToFile.c

loadTweetsFromFile.o: loadTweetsFromFile.c headerA3.h extraHeaderA3.h
	gcc -Wall -std=c99 -c loadTweetsFromFile.c

sortID.o: sortID.c headerA3.h extraHeaderA3.h
	gcc -Wall -std=c99 -c sortID.c

addNodeToList.o: addNodeToList.c headerA3.h extraHeaderA3.h
	gcc -Wall -std=c99 -c addNodeToList.c

displayMenu.o: displayMenu.c headerA3.h extraHeaderA3.h
	gcc -Wall -std=c99 -c displayMenu.c

matchStopWords.o: matchStopWords.c headerA3.h extraHeaderA3.h
	gcc -Wall -std=c99 -c matchStopWords.c

countTweets.o: countTweets.c headerA3.h extraHeaderA3.h
	gcc -Wall -std=c99 -c countTweets.c

deleteInsertNode.o: deleteInsertNode.c headerA3.h extraHeaderA3.h
	gcc -Wall -std=c99 -c deleteInsertNode.c

insertNode.o: insertNode.c headerA3.h extraHeaderA3.h
	gcc -Wall -std=c99 -c insertNode.c

freeTweets.o: freeTweets.c headerA3.h extraHeaderA3.h
	gcc -Wall -std=c99 -c freeTweets.c

clean:
	rm *.o phanThomasA3
